---
- name: Deploy Django application
  hosts: your_server
  vars:
    django_project_name: myproject
    django_project_repo: https://github.com/yourusername/myproject.git
    django_project_dir: /var/www/{{ django_project_name }}
  tasks:
    - name: Clone Git repository
      git:
        repo: "{{ django_project_repo }}"
        dest: "{{ django_project_dir }}"
        version: master
        clone: yes
      register: git_result

    - name: Install Python dependencies
      pip:
        requirements: "{{ django_project_dir }}/requirements.txt"
        virtualenv: "{{ django_project_dir }}/venv"
        state: present

    - name: Collect static files
      command: "{{ django_project_dir }}/venv/bin/python manage.py collectstatic --noinput"
      args:
        chdir: "{{ django_project_dir }}"

    - name: Restart web server
      service:
        name: nginx
        state: restarted

