---

- name: Clone Git repository
  git:
    repo: "https://github.com/hasnain28/django-test.git"
    dest: "/home/hasnain/github"
    key_file: "~/.ssh/id_rsa"

- name: Create Django project
  shell: |
   django-admin startproject myapp

- name: Create database tables
  shell: |
    cd myapp
    python3 manage.py migrate

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/myapp
    mode: 0644
  notify:
    - restart nginx

- name: Symlink nginx configuration
  file:
    src: /etc/nginx/sites-available/myapp
    dest: /etc/nginx/sites-enabled/myapp
    state: link
  notify:
    - restart nginx


    
    
      
