---
  2 
  3 - name: prepare home directory for www-data
  4   become: true
  5   file:
  6     group: www-data
  7     mode: 0755
  8     owner: www-data
  9     state: directory
 10     path: "/var/www/{{ item }}"
 11   loop:
 12     - .cache
 13     - .local
 14     - .config
 15 
 16 - name: Install pip
 17   become: true
 18   apt:
 19     name: python3-pip
 20     state: latest
 21 
 22 - name: Install Django using pip
 23   become: true
 24   become_user: www-data
 25   pip:
 26     name: django
 27     executable: pip3
 28     state: latest
 29 
 30 - name: Install Poetry using pip
 31   become: true
 32   become_user: www-data
 33   pip:
 34     name: poetry
 35     executable: pip3
 36     state: latest
 37 
 38 - name: prepare clone directory
 39   become: true
 40   file:
 41     group: www-data
 42     mode: 0755
 43     owner: www-data
 44     state: directory
 45     path: "/var/www/{{ project_name }}"
 46 
 47 - name: Clone Django project
 48   become: true
 49   become_user: www-data
 50   git:
 51     repo: "{{ project_repo }}"
 52     dest: "/var/www/{{ project_name }}"
        force: yes                                                                                                                                                                                 1,1 
        
 55 - name: Install project dependencies with Poetry
 56   become: true
 57   become_user: www-data
 58   shell: |
 59     poetry config virtualenvs.create true
 60     poetry install --no-interaction
 61     poetry lock --no-update
 62   args:
 63     chdir: "/var/www/{{ project_name }}"
 64 
 65 #- name: Run Django project
 66   #become: true
 67   #become_user: www-data
 68   #command: poetry run python3 manage.py runserver
 69   #command: /usr/local/lib/python3.9/dist-packages/poetry run python3 manage.py runserver
 70   #args:
 71     #chdir: "/var/www/{{ project_name }}"
 72 
 73 - name: Create systemd unit file
 74   become: true
 75   template:
 76     src: myproject.service.j2
 77     dest: /etc/systemd/system/myproject.service
 78   notify:
 79     - Reload systemd
 80 
 81 #- name: Reload systemd
 82   #become: true
 83   #systemd:
 84     #daemon_reload: yes
 85 
 86 - name: Start Django service
 87   become: true
 88   systemd:
 89     name: myproject.service
 90     state: started
 91     enabled: true
 92   notify:
 93     - Reload systemd



